version: "3.9"

services:
  backend:
    image: fastapi:latest
    build: ./fastapi              # Path to backend Dockerfile
    container_name: fastapi-backend
    expose:
      - "8000"               # Host:Container
    env_file:
      - ./.env 
    networks:
      - mynetwork

  frontend:
    image: frontendnext:latest
    build: ./frontendNext             # Path to frontend Dockerfile
    container_name: next-frontend
    expose:
      - "3000"               # Host:Container
    env_file:
      - ./.env 
    depends_on:
      - backend                   # Ensure backend starts first
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/block-probes.conf:/etc/nginx/conf.d/block-probes.conf:ro
      - ./nginx/logs:/var/log/nginx
      # TLS setting
      - ./nginx/certbot/www:/var/www/certbot        
      - ./nginx/letsencrypt:/etc/letsencrypt          
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge